name: Hello World (Multiplatform)

on:
  push:
    branches:
      - main
      - v*-branch
      - collab-*
  pull_request:
    branches:
      - main
      - v*-branch
      - collab-*
    paths:
      - 'scripts/build/**'
      - 'scripts/requirements*.txt'
      - '.github/workflows/hello_world_multiplatform.yaml'
      - 'SDK_VERSION'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: zephyr
          fetch-depth: 0

      - name: Rebase
        if: github.event_name == 'pull_request'
        env:
          BASE_REF: ${{ github.base_ref }}
          PR_HEAD: ${{ github.event.pull_request.head.sha }}
        working-directory: zephyr
        shell: bash
        run: |
          git config --global user.email "actions@zephyrproject.org"
          git config --global user.name "Github Actions"
          git rebase origin/${BASE_REF}
          git log --graph --oneline HEAD...${PR_HEAD}

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@1ec60c2940c6c4c19f973c043de0564e39998423 # v1.0.2
        with:
          app-path: zephyr
          toolchains: all

      - name: Build firmware
        working-directory: zephyr
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            EXTRA_TWISTER_FLAGS="-P native_sim --build-only"
          elif [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="-P native_sim --short-build-path -O/tmp/twister-out"
          fi
          ./scripts/twister --force-color --inline-logs -T samples/hello_world -v $EXTRA_TWISTER_FLAGS

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        with:
          if-no-files-found: ignore
          path:
            zephyr/twister-out/*/samples/hello_world/sample.basic.helloworld/build.log
