name: Create a Release

on:
  push:
    tags:
      - 'v*'
      - '!v*rc*'

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "TRIMMED_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@28cf8f33bc50f4c306f52e38fe3826717dea63dc # v1.3.0
        with:
          args: spdx -o zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

      - name: upload-results
        uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
        continue-on-error: true
        with:
          name: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
          path: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx

      - name: Create empty release notes body
        run: |
          echo "TODO: add release overview and notes link" > release-notes.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Zephyr ${{ steps.get_version.outputs.TRIMMED_VERSION }}
          body_path: release-notes.txt
          draft: true
          prerelease: true

      - name: Upload Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
          asset_name: zephyr-${{ steps.get_version.outputs.VERSION }}.spdx
          asset_content_type: text/plain
